site: eerFun.github.io
title: eerFun
description: >-
  Erfan Eivazi Digital Notebook
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
data-theme: dark # default theme "dark" | "light"

author:
  name: Erfan Eivazi (@eerFun)
  bio: Web Developer
  username: eerFun # general username
  github: eerFun # github username
  linkedin: eerFun
  telegram: eerFun
  email: eivazi.erfan@gmail.com # email address

# URL settings
url: "https://eerfun.github.io" # Domain Name of host. [username].github.io for github pages
#baseurl: "/" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: blog/:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
